files: '.py'
exclude: '.git'
default_stages: [commit]

repos:

  # Autoformatting (modifies staged files)

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["-l", "120", "--profile", "black"]

  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3
    hooks:
      - id: pycln
        args: ["--all"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["-l", "120"]

  # Code analysis (only checks staged files)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        name: mypy
        entry: "poetry run mypy"
        # language: system
        # types: [python]
        # require_serial: true
        args: ["--show-error-codes", "--show-error-context", "--pretty", "--show-absolute-path"]
        additional_dependencies: ['types-requests', 'types-attrs', 'pydantic']
        verbose: true
        fail_fast: true
  

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          "flake8-quotes==3.3.2"
        ]
        args: ["--max-line-length", "120", "--inline-quotes", "double"]
        fail_fast: true

  - repo: local
    hooks:
    -   id: endpoints-md
        name: endpoints-md
        entry: python endpoints.py
        language: system
        types: [python]
        fail_fast: true
